import pandas as pd

print("=" * 50)
print("FERTILITY DATASET")
print("=" * 50)
df1 = pd.read_csv("datasets/dataset1.csv")
print(df1.shape)
print(df1.columns.tolist())
print(df1.head())

print("\n" + "=" * 50)
print("CROP RECOMMENDATION DATASET")
print("=" * 50)
df2 = pd.read_csv("datasets/Crop_recommendation.csv")
print(df2.shape)
print(df2.columns.tolist())
print(df2.head())

print("\n" + "=" * 50)
print("FERTILIZER PREDICTION DATASET")
print("=" * 50)
df3 = pd.read_csv("datasets/Fertilizer Prediction.csv")
print(df3.shape)
print(df3.columns.tolist())
print(df3.head())

print("\n" + "=" * 50)
print("MISSING VALUES CHECK")
print("=" * 50)
print("\nCrop dataset missing values:")
print(df2.isnull().sum())
print("\nFertilizer dataset missing values:")
print(df3.isnull().sum())

print("\n" + "=" * 50)
print("CLASS BALANCE CHECK")
print("=" * 50)
print("\nCrop label counts:")
print(df2['label'].value_counts())
print("\nFertilizer Name counts:")
print(df3['Fertilizer Name'].value_counts())